# This file was generated by GoReleaser. DO NOT EDIT.
cask "apic" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "847b803ed0d4c7855bcca1e0cd5005acf7b8ffeabf14e62ab52c74c1ac9d94dd"
      url "https://github.com/hungovercoders/apic/releases/download/v#{version}/apic_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7983731fa07febbf3fae4e1036ab59dea04cab9f94fc405a82fb60f8fcdfc1b2"
      url "https://github.com/hungovercoders/apic/releases/download/v#{version}/apic_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1ee585c2bddb70e56522a94f689ddcf668476e872c78d76d709bb8ba0f7d9acd"
      url "https://github.com/hungovercoders/apic/releases/download/v#{version}/apic_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0226b624aaab2c2cbcec1683ebd356136fc5fe5bdda1a6e467964e43f2c2fa8f"
      url "https://github.com/hungovercoders/apic/releases/download/v#{version}/apic_#{version}_linux_amd64.tar.gz"
    end
  end

  name "apic"
  desc "Run .http request files from the terminal, CI or an AI agent"
  homepage "https://hungovercoders.github.io/apic/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apic"
  manpage "man/apic-completion-bash.1"
  manpage "man/apic-completion-fish.1"
  manpage "man/apic-completion-powershell.1"
  manpage "man/apic-completion-zsh.1"
  manpage "man/apic-completion.1"
  manpage "man/apic-curl.1"
  manpage "man/apic-demo.1"
  manpage "man/apic-describe.1"
  manpage "man/apic-env.1"
  manpage "man/apic-fmt.1"
  manpage "man/apic-history-clear.1"
  manpage "man/apic-history-diff.1"
  manpage "man/apic-history.1"
  manpage "man/apic-import.1"
  manpage "man/apic-init.1"
  manpage "man/apic-list.1"
  manpage "man/apic-lsp.1"
  manpage "man/apic-mcp.1"
  manpage "man/apic-run.1"
  manpage "man/apic-select.1"
  manpage "man/apic-session-clear.1"
  manpage "man/apic-session-cookies.1"
  manpage "man/apic-session.1"
  manpage "man/apic-skill-install.1"
  manpage "man/apic-skill.1"
  manpage "man/apic-snippet.1"
  manpage "man/apic-test.1"
  manpage "man/apic-ui.1"
  manpage "man/apic-validate.1"
  manpage "man/apic-version.1"
  manpage "man/apic.1"
  bash_completion "completions/apic.bash"
  fish_completion "completions/apic.fish"
  zsh_completion "completions/apic.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/apic"]
    end
  end

  # No zap stanza required
end
